version: "1.0"
info:
  model: int-scaffold
packages:
- name: DemoProject
  gitServerName: KritikasGitHubAccount
  gitUrl: https://github.com/KitNabber/DemoProject
  gitUsername: KitNabber
  gitBranch: main
